### ISSUE TITLE
asound.conf : meter and dmix plugin

### ISSUE THREAD

**Issue by alcoralcor** [project-owner/peppyalsa.doc#2]
Hello,
This is not a peppyalsa related issue but if there is a solution to my problem, that'll be an interesting thing to add to the documentation.
I have to use more than one application and I want a vumeter on the mixed stream.
My original asound.conf works with : 3 "plug" devices -> "dmix" device -> "hw " device
I now have to add "meter" device from peppyalsa but as "dmix" needs a "hw" slave, I can't use "meter" as "dmix" slave.
I have tried many configurations but I am not competent enough with ALSA to make peppyalsa work with dmix.
Has anybody managed to set up such a configuration ?
regards

**Comment by project-owner** [comment]
Hi, I'm not the expert in a complex ALSA configuration. I've posted your question on diyAudio forum, hopefully it will be answered there.
https://www.diyaudio.com/community/threads/peppyalsa-alsa-plugin-for-vu-meters-and-spectrum-analyzers.328688/post-7256245
Best regards.

**Comment by pavhofman** [comment]
I do not think there is a simple alsa-only way. Dmix does allow  hw slave only https://github.com/alsa-project/alsa-lib/blob/fea9fc229892695afa4e41598ebb79ea58ffb4b2/src/pcm/pcm_dmix.c#L1003-L1007 . IMO either some ugly hacking with the loopback device like in https://unix.stackexchange.com/a/194631 , or using pipewire (or pulseaudio) instead of alsa dmix.

**Comment by alcoralcor** [comment]
I can send on the loopback but I didn't find a solution to capture the loopback with ALSA. I thought the copy plugin would be useful but I couldn't do it.
Thanks for your help. You confirm there's probably no pure ALSA solution.
I'll have a try with pipewire/ALSA later.
